book_rental/urls.py
from django.conf.urls import url
from . import views

app_name = 'book_rental'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^createcategoryform/$', views.createcategoryform, name='createcategoryform'),
    url(r'^create_coustomer/$', views.create_coustomer, name='create_coustomer'),
    url(r'^(?P<category_id>[0-9]+)/book_selection/$', views.book_selection, name='book_selection'),
    url(r'^(?P<category_id>[0-9]+)/add_book/', views.add_book, name='add_book'),
    url(r'^(?P<category_id>[0-9]+)/calculate/', views.calculate, name='calculate'),

]

book_rental_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('book_rental.urls'))
]

book_rental/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

# Create your models here.


class BookCategory(models.Model):
    """Class representing a Book category."""
    book_category_name = models.CharField(max_length=150)
    cost = models.FloatField()

    def __str__(self):
        return self.book_category_name


class Book(models.Model):
    """Class representing a Book rented."""
    book_category = models.ForeignKey(BookCategory,
                                      related_name='bookcategory',
                                      on_delete=models.CASCADE,
                                      )
    book_name = models.CharField(max_length=100)
    author_name = models.CharField(max_length=100)
    cost = models.FloatField(default=0)

    start_date = models.DateTimeField(_('started at'), auto_now_add=True,
                                      null=False, blank=False)
    end_date = models.DateTimeField(_('ended at'), auto_now_add=True,
                                      null=False, blank=False)

    def __str__(self):
        return self.book_name


class Coustomer(models.Model):
    """Class representing a Coustomer"""
    name = models.CharField(max_length=300, null=True, blank=True)
    address = models.TextField(max_length=300, null=True, blank=True)
    cost = models.FloatField(default=0)
    book = models.ForeignKey(Book)

    def __str__(self):
        return self.name

book_rental/forms.py
from django import forms
from book_rental.models import BookCategory, Coustomer, Book


class BookCategoryForm(forms.ModelForm):
    class Meta:
        model = BookCategory
        fields = '__all__'


class CoustomerForm(forms.ModelForm):
    class Meta:
        model = Coustomer
        fields = '__all__'


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ('book_category',)

book_rental/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse, get_object_or_404

from book_rental.models import BookCategory, Book, Coustomer
from django.http import HttpResponseRedirect, HttpResponse
from book_rental.forms import BookCategoryForm,BookForm, CoustomerForm


def index(request):
    category_list = BookCategory.objects.all()
    return render(request, 'book_rental/index.html', {'category_list': category_list})


def createcategoryform(request):
    if request.method == "POST":
        form = BookCategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('book_rental:index'))
    form = BookCategoryForm()
    return render(request, "book_rental/categoryform.html", {'form': form})


def book_selection(request, category_id):
    bookcategory = get_object_or_404(BookCategory, id=category_id)
    if request.method == 'POST':
        days=request.POST['days']
        check_values = request.POST.getlist('books[]')
        number_of_books=len(check_values)
        result=number_of_books*bookcategory.cost
        result*= int(days)
        return render(request, 'book_rental/calculate.html', {'result': result})
        # return HttpResponseRedirect(reverse('book_rental:calculate'))
    books = Book.objects.filter(book_category=bookcategory)
    return render(request, 'book_rental/bookcategory.html', {'bookcategory': bookcategory, 'books': books})

# def book_selection(request, category_id):
#     bookcategory = get_object_or_404(BookCategory, id=category_id)
#     if request.method == "POST":
#         bookcategory.book_set.create(
#             book_name=request.POST['book_name'],
#             author_name=request.POST['author_name'],
#         )
#
#
#     return render(request, 'book_rental/bookcategory.html', {'bookcategory': bookcategory})


def add_book(request, category_id):
    bookcategory = get_object_or_404(BookCategory, id=category_id)
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.book_category = bookcategory
            instance.save()
            return HttpResponseRedirect(reverse('book_rental:book_selection', args=[category_id, ]))
    form = BookForm()
    return render(request,'book_rental/add_book.html', {'form': form})


def calculate(request, category_id):
    return HttpResponse('success')


def create_coustomer(request):
    if request.method == "POST":
        form = CoustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('book_rental:index'))
    form = CoustomerForm()
    return render(request, "book_rental/customerform.html", {'form': form})

book_rental/templates/book_rental/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NewBook</title>
</head>
<body>
<h1>Add a Book</h1>
<form action="" method="post" >
   {% csrf_token %}
  {% for field in form %}
    {{ field.label_tag }} {{ field }}<br>
  {% endfor %}
    <input type="submit" value='create'>
</form>
</body>
</html>

book_rental/templates/book_rental/bookcategory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{bookcategory}}</h1>

Rs{{bookcategory.cost}} only per day<br><br>
<form action="" method="post">
    {% csrf_token %}
     Number of days :<input type="text" name="days"><br>
{% for book in books %}
<input type="checkbox" name="books[]" value="{{book.id}}">
{{book.book_name}}<br><br>
{% endfor %}
    <input type="submit" value="add" />
</form>
<a href = '{% url "book_rental:add_book" bookcategory.id %}'>Add Book</a><br><br>
<a href = '{% url "book_rental:calculate" bookcategory.id %}'>Calculate</a><br><br>
</body>
</html>

book_rental/templates/book_rental/calculate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bill payment</title>
</head>
<body>

<h2>Amount to be paid = {{result}}</h2>
<a href = '{% url "book_rental:index" %}'>Home</a>
</body>
</html>

book_rental/templates/book_rental/categoryform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CreateForm</title>
</head>
<body>
<form action="" method="post" >
   {% csrf_token %}
  {% for field in form %}
    {{ field.label_tag }} {{ field }}<br>
  {% endfor %}
    <input type="submit" value='create'>
</form>
</body>
</html>

book_rental/templates/book_rental/customerform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>coustomer form</title>
</head>
<body>
<form action="" method="post" >
   {% csrf_token %}
  {% for field in form %}
    {{ field.label_tag }} {{ field }}<br>
  {% endfor %}
    <input type="submit" value='create'>
</form>
</body>
</html>

book_rental/templates/book_rental/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HomePage</title>
</head>
<body>
<h1>Hello</h1>

{% for category in category_list %}

<a href = '{% url "book_rental:book_selection" category.id %}'>{{category.book_category_name}}</a><br><br>
{% endfor %}

<a href = '/books/createcategoryform'>Add new category</a><br><br>
</body>
</html>